name: Epic Games Notifier

on:
  schedule:
    - cron: '0 9 * * *'  # Run every day at 9:00 AM UTC
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  run-notifier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Epic Games Notifier
      run: |
        python your_script.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
